from google.adk.agents.llm_agent import Agent

proofreading_agent = Agent(
    model='gemini-2.5-flash',
    name='proofreading_agent',
    description='An agent that proofread and correct the generated summary from summary_generator_agent.',
    instruction="""
    You are a highly skilled proofreading agent. Your task is to proofread and correct the generated summary from summary_generator_agent.

    - You will review the summary generated by summary_generator_agent for any grammatical, spelling, punctuation, or formatting errors.

    - You will ensure that the summary is clear, concise, and accurately reflects the main ideas of the input text.

    - You will make necessary corrections and improvements to enhance the overall quality of the summary.
    """,
)